# Build stage
FROM node:22-alpine AS build

WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm ci

# Copy source code
COPY . .

# Build the app
#RUN npm run build

# Production stage
#FROM nginx:alpine

# Copy built assets from build stage
#COPY --from=build /app/build /usr/share/nginx/html

# Copy nginx configuration
#COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port
EXPOSE 8000

# Start nginx
#CMD ["nginx", "-g", "daemon off;"]
CMD ["npm", "start"]